"""Constants used by the rinnai touch component."""

RINNAI = "rinnai"
ICON = "mdi:fan"
DOMAIN = "rinnaitouch"
DEFAULT_NAME = "Rinnai Touch"
UNIT_FAN_SPEED = "ø"
UNIT_COMFORT_LEVEL = "±"
PRESET_HEAT = "Heating"
PRESET_COOL = "Cooling"
PRESET_EVAP = "Evap"
FAN_ONLY = "Fan Only"
CONF_TEMP_SENSOR = "external_temperature_sensor"
CONF_ZONE_A = "Zone A"
CONF_ZONE_B = "Zone B"
CONF_ZONE_C = "Zone C"
CONF_ZONE_D = "Zone D"
